version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE:     ${DB_NAME}
      MYSQL_USER:         ${DB_USER}
      MYSQL_PASSWORD:     ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - arquetipo-net


  arquetipo-api:
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
      context: ./Arquetipo.Api
      dockerfile: Dockerfile
    image: arquetipo-api:latest
    container_name: arquetipo-api
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - arquetipo-net

volumes:
  mysql-data:
  
networks:
  arquetipo-net:
    external: true