# .github/workflows/build-api-in-docker.yml
name: Build Arquetipo.Api in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show .NET SDK version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore Arquetipo.Api/Arquetipo.Api.csproj

      - name: Build in Release
        run: dotnet build Arquetipo.Api/Arquetipo.Api.csproj --configuration Release --no-restore

      - name: Success message
        run: echo "✅ Arquetipo.Api built successfully inside Docker container"