name: Actualizar Wiki desde README

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Checkout de la Wiki
      - name: Checkout de la Wiki
        uses: actions/checkout@v3
        with:
          # Clona el repo de la wiki del mismo repositorio
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      # 3. Copiar README.md a la Wiki
      - name: Copiar README a la Wiki
        run: |
          cp README.md wiki/Home.md

      # 4. Commit y push en la Wiki
      - name: Commit y push en la Wiki
        working-directory: wiki
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Home.md
          git diff --staged --quiet || git commit -m "📖 Actualizar Home desde README"
          git push origin main
